version: 2

jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: python setup
          command: pyenv global 3.5.2 && pip install selenium pyyaml
      - run:
          name: docker-compose up -d
          command: cd docker && docker-compose up -d
      - run:
          name: test execute
          command: python easy-Tester/test/circleci_test.testsuites.py
      - run:
          name: docker-compose down
          command: cd docker && docker-compose down
      - store_test_results:
          path: easy-Tester/test/reports
      - store_artifacts:
          path: easy-Tester/test/artifacts
