version: 2

jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
    - checkout
    - run:
        name: git submodule update
        command: |
          git submodule init
          git submodule update
          git submodule foreach git pull origin master
          cd universe
          git checkout -b develop origin/develop
    - persist_to_workspace:
        root: .
        paths:
          - .
  test:
    machine:
      image: circleci/classic:edge
    steps:
      - attach_workspace:
          at: .
      - run:
          name: python setup
          command: pyenv global 3.5.2 && pip install --upgrade pip
      - run:
          name: Universe setup
          command: sh universe/setup.sh
      - run:
          name: docker-compose up -d
          command: cd docker && docker-compose up -d
      - run:
          name: test execute
          command: universe test run
      - run:
          name: docker-compose down
          command: cd docker && docker-compose down
      - store_test_results:
          path: universe-e2e/reports
      - store_artifacts:
          path: universe-e2e/artifacts

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
