version: 2

jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
    - checkout
    - persist_to_workspace:
        root: .
        paths:
          - .
  test:
    machine:
      image: circleci/classic:edge
    steps:
      - attach_workspace:
          at: .
      - run:
        name: python setup
        command: pyenv global 3.5.2 && pip install --upgrade pip
      - run:
          name: easy-Tester setup
          command: sh easy-Tester/setup.sh
      - run:
          name: docker-compose up -d
          command: cd docker && docker-compose up -d
      - run:
          name: test execute
          command: eT test run
      - run:
          name: docker-compose down
          command: cd docker && docker-compose down
      - store_test_results:
          path: eT-test/reports
      - store_artifacts:
          path: eT-test/artifacts

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
