version: 2

jobs:
  build:
    machine:
      image: circleci/classic:edge
    working_directory: ~/var/www/html
    steps:
      - checkout
      - run:
          name: docker-compose
          command: docker-compose --version
      - run:
          name: python
          command: python --version
      - run:
          name: python2
          command: python2 --version
      - run:
          name: python3
          command: python3 --version
      - run:
          name: test start
          command: echo "-----test start-----"
#      - run:
#          name: test exec
#          command: python3.6 easy-Tester/test/circleci_test.testsuites.py
      - run:
          name: test end
          command: echo "-----test end-----"
