version: 2
jobs:
  build:
    docker:
    - image: kptakami/php-apache-python3:7.2-alpine
    steps:
    - checkout
    - run:
        name: Greeting
        command: echo Hello, world.
    - run:
        name: Print the Current Time
        command: date
