version: '3'

services:

  # Web
  web:
    build: ./docker_file/web/
    ports:
      - 8888:80
    volumes:
      - ./../:/var/www/localhost/htdocs/web
      - ./../../../eT-test:/var/www/localhost/htdocs/eT-test
